[project]
authors = [{name = "IgnorantCopy", email = "231880174@smail.nju.edu.cn"}]
dependencies = ["kaleido>=0.2.1,<0.4.2"]
name = "Neuroscience"
requires-python = ">=3.8,<3.9"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
neuroscience = { path = ".", editable = true }

[tool.pixi.feature.gpu.system-requirements]
cuda = "12.1"

[tool.pixi.feature.gpu.dependencies]
cuda-version = "12.1.*"
pytorch-gpu = "*"

[tool.pixi.environments]
default = ["gpu"]

[tool.pixi.tasks]

[tool.pixi.dependencies]
psychopy = ">=2022.2.5,<2023"
pixi-pycharm = ">=0.0.8,<0.0.9"
brian2 = ">=2.5.1,<3"
notebook = ">=7.2.2,<8"
plotly = ">=5.24.1,<6"
scikit-learn = ">=1.3.2,<2"
pytorch = ">=2.1.0,<3"
torchvision = ">=0.16.1,<0.17"
